### ISSUE TITLE
QA - Website Builder - Layout - Layout Page is disappear when user click on edit option of newly created Layout.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#321]
Create Project.
Click on Layout Folder.
Click on New Layout Option and Create new Layout.
Click on Newly Created Layout.
Observe No Default Grid is display in besides.
![layout page is disappear when user click on edit option of newly created layout](https://user-images.githubusercontent.com/36226408/36089226-c00cba9c-1000-11e8-8b0b-d85592e7d0ec.jpg)

**Comment by gkumar9** [comment]
Yes. That's because this new layout you created is supposed to be a custom layout of you. So default grid will not be shown. For default we have (default.layout) file.

Also, regarding edit as its a blank file, it's showing no line of code in the edit. Try adding some grid component and then click edit.

**Comment by acharotariya** [comment]
ohk.
Got it.
